location /api/v1/users/ {
    include /etc/nginx/snippets/require-bearer.conf;
    set $upstream identity-api:8081;
    include /etc/nginx/snippets/proxy-common.conf;
    proxy_pass http://$upstream;
}
